// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHlLE5aHjIuSO-Q1OsrtliwQpTq37OLM',
    appId: '1:639186771500:web:67dbac38870e731f253b89',
    messagingSenderId: '639186771500',
    projectId: 'lightychat1',
    authDomain: 'lightychat1.firebaseapp.com',
    storageBucket: 'lightychat1.appspot.com',
    measurementId: 'G-J70ZKQZ4XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-Ntj6LktpHqp5D7vB3IbKWNwJvLLwVo',
    appId: '1:639186771500:android:5fd6abd7fddc91f6253b89',
    messagingSenderId: '639186771500',
    projectId: 'lightychat1',
    storageBucket: 'lightychat1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ExnnP833qk5AceDaV6mM6-micV8MpJM',
    appId: '1:639186771500:ios:5bc2584675926061253b89',
    messagingSenderId: '639186771500',
    projectId: 'lightychat1',
    storageBucket: 'lightychat1.appspot.com',
    iosClientId: '639186771500-g3t8404j53kevosd3rbcq0lvtkb3ejrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightyChat',
  );
}
